### ISSUE TITLE
Having problems client integration with flutter

### ISSUE THREAD

**Issue by ghost** [KonstantinKai/uploadcare_client#1]
While I am trying to upload a picture using uploadcare,
 I do not receive a further response. Maybe I am missing something, but I have been following documentations.

![ezgif com-optimize](https://user-images.githubusercontent.com/3517778/71816711-b1484380-30ad-11ea-899e-122db0f754c0.gif)

**Comment by KonstantinKai** [comment]
@shahparan, hello! It seems to be You have an exception which doesn't handle by UI, Try to handle `Error` state in UI.
Put a new code here: https://github.com/KonstantinKai/uploadcare_client/blob/master/example/lib/main.dart#L226

**Comment by KonstantinKai** [comment]
UPD: @shahparan I've updated the example project, you can check your error now. Please reopen the issue if an error will occur related to the source code
