### ISSUE TITLE
GroupInfoEntity not exported

### ISSUE THREAD

**Issue by ObserverMoment** [KonstantinKai/uploadcare_client#2]
Hi KonstantinKai!

Thanks for this library, its making my life so much easier trying to integrate my Flutter app with Uploadcare, really nice work!

I've noticed that GroupInfoEntity is not exported in the main package. This is entities/entities.dart, you can see that group.dart is missing.

export 'file_info.dart';
export 'list.dart';
export 'progress.dart';
export 'url.dart';
export 'video_encoding.dart';
export 'common.dart';
export 'faces.dart';

Could you add it and update to pub please?

Cheers,

Rich

**Comment by KonstantinKai** [comment]
Hi @ObserverMoment!
I'm sorry for the long response because I was on vacation :)
Fixed in `2.1.1`!!!

**Comment by ObserverMoment** [comment]
Awesome, thanks. Hope you had a good holiday!
