### ISSUE TITLE
Null Safety Update, Library Splitting

### ISSUE THREAD

**Issue by ObserverMoment** [KonstantinKai/uploadcare_client#4]
Hey Konstantin, are there any plans to migrate this package to null safety? 

Package has been really useful and it would be nice to maintain / update it.

Thanks,

Rich

**Comment by KonstantinKai** [comment]
Hey @ObserverMoment, yeah, I have a plan to do this along with a package spliting

**Comment by KonstantinKai** [comment]
`Null safety` will be available soon

**Comment by KonstantinKai** [comment]
Released:
[uploadcare_client@^3.0.0](https://pub.dev/packages/uploadcare_client)
[uploadcare_flutter@^1.0.0](https://pub.dev/packages/uploadcare_flutter)

**Comment by ObserverMoment** [comment]
Amazing - great news! Thanks Konstantin
