### ISSUE TITLE
Upload images on web

### ISSUE THREAD

**Issue by tha022** [KonstantinKai/uploadcare_client#6]
Do you have a guide on how to work with images uploaded from browser? Browsers doesn't have access to the file system as on mobile platforms. 

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/1275358/169649881-1b419856-8fca-42b3-b6e0-1c6c6597391e.png">

In advance thanks!

**Comment by KonstantinKai** [comment]
Hello @tha022, you can refer to https://github.com/KonstantinKai/uploadcare_client/blob/master/uploadcare_flutter_example/lib/picker_web.dart

It is a full example for uploading case.

**Comment by tha022** [comment]
Thanks for reply Konstantin, highly appreciated!

I saw I had to change the isolate property to false, which makes sense as browsers don't supported it
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/1275358/169918379-249918a1-a556-4be9-b2ff-00870b9e8e82.png">


But quick other question if I may, both in your code and mine I get this 400 from uploadcare. Any idea?
<img width="1760" alt="image" src="https://user-images.githubusercontent.com/1275358/169918288-0c6800eb-ae2d-4113-87a0-090cec9a529f.png">


And yet again, thanks for your time!

**Comment by KonstantinKai** [comment]
Yeah, the web platform has some limitations for use.

- It's impossible to use AuthSchemeRegular auth scheme on the web with fetch API because the Date request header is forbidden for XMLRequest https://fetch.spec.whatwg.org/#forbidden-header-name.
- It's impossible to run the upload process in a separate isolate on the web environment.

Switch to `AuthSchemeSimple`, and upload will work.
```
final client = UploadcareClient.withSimpleAuth(
  publicKey: 'UPLOADCARE_PUBLIC_KEY',
  privateKey: 'UPLOADCARE_PRIVATE_KEY',
  apiVersion: 'v0.5',
);
```

**Comment by tha022** [comment]
Perfect, thanks a lot, that worked as charm!

![image](https://user-images.githubusercontent.com/1275358/170028541-9dc24778-d467-43c0-b6c8-6fda390399e1.png)
