### ISSUE TITLE
Files screen crash when GET files next and previous response properties are null

### ISSUE THREAD

**Issue by tha022** [KonstantinKai/uploadcare_client#7]
Hi 

Think I found an issue.

Files screen crash when GET files next and previous response properties are null.
In Uploadcare's API description those properties are nullable
https://uploadcare.com/api-refs/rest-api/v0.5.0/#operation/filesList

See screen shots

![image](https://user-images.githubusercontent.com/1275358/170680094-31e6a84e-b80f-46d4-b61d-5130eff32c7e.png)
![image](https://user-images.githubusercontent.com/1275358/170680135-4640407f-fad0-49d2-b7a4-e3fabd58abd6.png)
![image](https://user-images.githubusercontent.com/1275358/170680240-d0c7fb37-8cb1-4808-a544-df672ec03616.png)
![image](https://user-images.githubusercontent.com/1275358/170680378-6fa95ae2-e79c-47eb-9945-03ce4be43034.png)

Thanks!

**Comment by KonstantinKai** [comment]
@tha022 Hello, tnx. Yesterday I published a huge update where this was fixed.

https://pub.dev/packages/uploadcare_client/changelog

**Comment by tha022** [comment]
Nice, saw now, and I see a lot neat features, I'll upgrade and test out, thanks!

**Comment by KonstantinKai** [comment]
Fixed in `6.0.0`
